# Template to push Docker image to Azure Container Registry

parameters:
  containerRegistry: ""
  acrName: ""
  imageName: ""
  dockerfilePath: ""
  buildContext: ""

jobs:

- job: PushImageToACR
  displayName: 'Push Docker Image to ACR'
  pool:
    name: 'Default'

  steps:

  - task: PowerShell@2
    displayName: "Display Current Job Variables"
    inputs:
      targetType: 'inline'
      script: |
        Get-ChildItem Env: | ForEach-Object { Write-Host "$($_.Name)=$($_.Value)" }


  - task: Docker@2
    displayName: Build Image
    inputs:
      containerRegistry: ${{ parameters.containerRegistry }}
      repository: ${{ parameters.imageName }}
      command: 'build'
      Dockerfile: '$(dockerfilePath)'
      buildContext: '$(buildContext)'
      tags: |
        $(Build.BuildId)
        latest

  - task: Docker@2
    displayName: Push Image
    inputs:
      containerRegistry: ${{ parameters.containerRegistry }}
      repository: ${{ parameters.imageName }}
      command: 'push'
      tags: |
        $(Build.BuildId)
        latest