# Template to push Docker image to Azure Container Registry

parameters:
  azureSubscription: ""
  acrName: ""
  imageName: ""
  dockerfilePath: ""
  buildContext: ""

jobs:

- job: PushImageToACR
  displayName: 'Push Docker Image to ACR'
  pool:
    name: 'Default'

  steps:

  - task: PowerShell@2
    displayName: "Display Current Job Variables"
    inputs:
      targetType: 'inline'
      script: |
        Get-ChildItem Env: | ForEach-Object { Write-Host "$($_.Name)=$($_.Value)" }

  - task: AzureCLI@2
    displayName: 'Login to ACR'
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      scriptType: pscore
      scriptLocation: 'inlineScript'
      inlineScript: |
        az acr login --name ${{ parameters.acrName }}

  # Since we are using Apple silicon, we need to use linux/amd64 platform for building and pushing the image to ACR

  - script: |
      echo "Setting up Docker Buildx for multi-platform builds..."
      docker buildx create --use --name mybuilder || docker buildx use mybuilder
      docker buildx inspect --bootstrap
    displayName: 'Create/Use buildx builder'

  - script: |
      echo "Building Docker image..."
      docker buildx build
        --platform linux/amd64
        -t ${{ parameters.acrName }}.azurecr.io/${{ parameters.imageName }}:$(Build.BuildId)
        -t ${{ parameters.acrName }}.azurecr.io/${{ parameters.imageName }}
        -f ${{ parameters.dockerfilePath }}
        ${{ parameters.buildContext }}
        --load
    displayName: 'Build AMD64 Image'

  - script: |
      echo "Pushing Docker image to ACR..."
      docker push ${{ parameters.acrName }}.azurecr.io/${{ parameters.imageName }}:$(Build.BuildId)
      docker push ${{ parameters.acrName }}.azurecr.io/${{ parameters.imageName }}
    displayName: 'Push Image to ACR'