# Pipeline for Application (Docker → ACR → Web App)

trigger: none

name: 'Image-Deployment-$(Date:yyyyMMdd)$(Rev:.r)'

stages:
- stage: DEV_Build_And_Validate_Image
  displayName: 'DEV Image Validation'
  variables:
    - template: ../Variables/dev.yml
  jobs:
  - template: ../Templates/build.template.imageupload.yml
    parameters:
      imageName: $(imageName)
      dockerfilePath: $(dockerfilePath)
      buildContext: $(buildContext)


- stage: DEV_Push_Image_To_ACR
  displayName: 'DEV Image Upload'
  dependsOn: DEV_Build_And_Validate_Image
  variables:
    - template: ../Variables/dev.yml
  jobs:
  #------------Approvals-----------------------#
  - deployment: DEV
    pool: 'Default'
    environment: DEV_INFRA_APPROVAL
  #---------------------------------------------#
  - template: ../Templates/release.template.imageupload.yml
    parameters:
      azureSubscription: 'devops-assignment-conn'
      acrName: $(acrName)
      imageName: $(imageName)

- stage: PROD_Build_And_Validate_Image
  displayName: 'PROD Image Validation'
  variables:
    - template: ../Variables/prod.yml
  jobs:
  - template: ../Templates/build.template.imageupload.yml
    parameters:
      imageName: $(imageName)
      dockerfilePath: $(dockerfilePath)
      buildContext: $(buildContext)

- stage: PROD_Push_Image_To_ACR
  displayName: 'PROD Image Upload'
  dependsOn: PROD_Build_And_Validate_Image
  variables:
    - template: ../Variables/prod.yml
  jobs:
  #------------Approvals-----------------------#
  - deployment: PROD
    pool: 'Default'
    environment: PROD_INFRA_APPROVAL
  #---------------------------------------------#
  - template: ../Templates/release.template.imageupload.yml
    parameters:
      azureSubscription: 'devops-assignment-conn'
      acrName: $(acrName)
      imageName: $(imageName) 