variables:
  imageName: python-api
  dockerfilePath: "Infrastructure/Docker/fastapi_dockerfile"
  buildContext: .

  acrName: dev-containerregistry
  resourceGroup: dev-rg
  containerAppName: dev-containerapp