variables:
  imageName: python-api
  dockerfilePath: "Infrastructure/Docker/fastapi_dockerfile"
  buildContext: .

  acrName: prod-containerregistry
  resourceGroup: prod-rg
  containerAppName: prod-containerapp